import type { ScopeTemplate } from "@/lib/scopes/templates/types";

const kitchenAllocations = {
  labour: 30,
  materials: 35,
  subcontractors: 25,
  allowances: 5,
  contingency: 5,
};

export const kitchenRenovationScopeTemplate: ScopeTemplate = {
  scopeTypeKey: "kitchen_renovation",
  label: "Kitchen renovation",
  workAreaTypeKey: "Kitchen renovation",
  category: "renovation",
  aliases: [
    "kitchen",
    "kitchen renovation",
    "kitchen remodel",
    "kitchen reno",
    "new kitchen",
  ],
  quantity: {
    primaryUnit: "each",
    requiredFields: ["kitchen.kitchen_size_type"],
  },
  facts: {
    required: [
      {
        key: "kitchen.kitchen_size_type",
        label: "Kitchen size",
        type: "select",
        questionText: "Is this a small, medium or large kitchen?",
        options: [
          { value: "small", label: "Small" },
          { value: "medium", label: "Medium" },
          { value: "large", label: "Large" },
          { value: "unknown", label: "Not sure yet" },
        ],
        affectsEstimate: true,
        affectsConfidence: true,
      },
      {
        key: "kitchen.layout_changing",
        label: "Layout changing",
        type: "select",
        questionText: "Is the layout changing?",
        affectsEstimate: true,
        affectsConfidence: true,
      },
      {
        key: "kitchen.appliances_client_supplied",
        label: "Appliances client supplied",
        type: "select",
        questionText: "Are appliances client supplied?",
        affectsEstimate: true,
        affectsConfidence: true,
      },
      {
        key: "kitchen.benchtop_type",
        label: "Benchtop type",
        type: "select",
        questionText: "What benchtop should I assume?",
        options: [
          { value: "laminate", label: "Laminate" },
          { value: "engineered_stone", label: "Engineered stone" },
          { value: "premium", label: "Premium stone" },
          { value: "not_sure", label: "Not sure yet" },
        ],
        affectsEstimate: true,
        affectsConfidence: true,
      },
      {
        key: "kitchen.plumbing_changes",
        label: "Plumbing changes",
        type: "select",
        questionText: "Are plumbing or electrical changes required?",
        affectsEstimate: true,
        affectsConfidence: true,
      },
      {
        key: "kitchen.electrical_changes",
        label: "Electrical changes",
        type: "select",
        questionText: "Are electrical changes required?",
        affectsEstimate: true,
        affectsConfidence: true,
      },
    ],
    useful: [
      {
        key: "kitchen.demolition_required",
        label: "Demolition required",
        type: "select",
        questionText: "Is demolition of the existing kitchen required?",
        affectsEstimate: true,
        affectsConfidence: true,
      },
      {
        key: "kitchen.floor_area_m2",
        label: "Floor area",
        type: "number",
        unit: "m²",
        questionText: "Approximate kitchen floor area?",
        affectsEstimate: true,
        affectsConfidence: true,
      },
      {
        key: "kitchen.cabinetry_length_m",
        label: "Cabinetry length",
        type: "number",
        unit: "m",
        questionText: "Approximate cabinetry run length?",
        affectsEstimate: true,
        affectsConfidence: true,
      },
      {
        key: "kitchen.cabinetry_level",
        label: "Cabinetry level",
        type: "select",
        questionText: "What cabinetry level should I assume?",
        affectsEstimate: true,
        affectsConfidence: true,
      },
    ],
    optional: [
      {
        key: "kitchen.splashback",
        label: "Splashback included",
        type: "select",
        questionText: "Is splashback included?",
      },
      {
        key: "kitchen.flooring_included",
        label: "Flooring included",
        type: "select",
        questionText: "Is new flooring included?",
      },
    ],
  },
  pricing: {
    supported: true,
    pricingMode: "benchmark_rate",
    defaultRateUnit: "each",
    benchmarkRates: { budget: 25000, standard: 38000, premium: 55000 },
    defaultAllocations: kitchenAllocations,
    calculationType: "kitchen_size",
    layoutChangeModifier: 1.15,
    componentAllocation: {
      labour: [
        { key: "demo_labour", label: "Demo labour", weight: 3, defaultIncluded: true },
        { key: "carpentry_labour", label: "Cabinetry labour", weight: 5, defaultIncluded: true },
        { key: "project_management", label: "Project management", weight: 2, defaultIncluded: true },
        { key: "installation_labour", label: "Installation labour", weight: 4, defaultIncluded: true },
      ],
      materials: [
        { key: "cabinetry_materials", label: "Cabinetry materials", weight: 5, defaultIncluded: true },
        { key: "benchtop_materials", label: "Benchtop materials", weight: 4, defaultIncluded: true },
        {
          key: "appliance_allowance",
          label: "Appliance allowance",
          weight: 3,
          defaultIncluded: true,
          excludeWhenFacts: ["kitchen.appliances_client_supplied"],
        },
        { key: "consumables", label: "Consumables", weight: 2, defaultIncluded: true },
      ],
      subcontractors: [
        { key: "plumber", label: "Plumber", weight: 4, defaultIncluded: true },
        { key: "electrician", label: "Electrician", weight: 4, defaultIncluded: true },
        { key: "tiler", label: "Splashback tiler", weight: 2, defaultIncluded: true },
      ],
      allowances: [
        {
          key: "demolition_allowance",
          label: "Demolition allowance",
          weight: 3,
          includeWhenFacts: ["kitchen.demolition_required"],
          defaultIncluded: true,
        },
        { key: "cartage_allowance", label: "Cartage allowance", weight: 2, defaultIncluded: true },
        {
          key: "unknown_conditions",
          label: "Unknown conditions allowance",
          weight: 2,
          defaultIncluded: true,
        },
      ],
    },
  },
  constraints: { applicable: [] },
  assumptions: {
    default: [
      "Kitchen pricing is a rough allowance — confirm rates before relying on this.",
    ],
  },
  exclusions: { default: [] },
  followUps: { dependentQuestions: [] },
  estimateBreakdown: { defaultLineGroups: [] },
};
