import { YES_NO_UNSURE } from "@/lib/scope-templates/shared";
import type { ScopeTemplate } from "@/lib/scope-templates/types";

export const bathroomRenovationTemplate: ScopeTemplate = {
  key: "bathroom_renovation",
  name: "Bathroom renovation",
  workAreaTypeKey: "Bathroom renovation",
  category: "Interior",
  aliases: [
    "bathroom",
    "shower",
    "vanity",
    "toilet",
    "waterproofing",
    "ensuite",
    "wet room",
  ],
  description: "Bathroom renovation including waterproofing, tiling, fixtures and layout changes.",
  requiredFacts: [
    {
      key: "bathroom.floor_area_m2",
      label: "Bathroom floor area",
      unit: "m²",
      required: true,
      extractionPatterns: [
        /bathroom\s*(?:floor\s*)?(?:area|size)?\s*(?:of|about|approx(?:imately)?\.?|is)?\s*(\d+(?:\.\d+)?)\s*(?:m2|m²|sqm)/i,
        /(\d+(?:\.\d+)?)\s*(?:m2|m²|sqm)\s*bathroom/i,
      ],
      extractValue: (m) => m[1] ?? null,
    },
  ],
  optionalFacts: [
    {
      key: "bathroom.layout_changing",
      label: "Layout changing",
      required: false,
      extractionPatterns: [
        /\blayout\s+chang/i,
        /\brelocat(e|ing)\s+(?:shower|toilet|vanity)/i,
        /\bmoving\s+(?:shower|toilet|vanity)/i,
      ],
      extractValue: () => "yes",
    },
    {
      key: "bathroom.waterproofing_included",
      label: "Waterproofing included",
      required: false,
      extractionPatterns: [/\bwaterproof/i],
      extractValue: () => "yes",
    },
  ],
  questions: [
    {
      questionKey: "bathroom.floor_area_m2",
      label: "Approximate bathroom floor area?",
      type: "number",
      unit: "m²",
      required: true,
      affectsEstimate: true,
      placeholder: "e.g. 6",
    },
    {
      questionKey: "bathroom.layout_changing",
      label: "Is the layout changing?",
      type: "select",
      required: true,
      affectsEstimate: true,
      options: [...YES_NO_UNSURE],
    },
    {
      questionKey: "bathroom.finish_level",
      label: "What finish level is expected?",
      type: "select",
      required: false,
      affectsEstimate: true,
      options: [
        { value: "budget", label: "Budget / basic" },
        { value: "standard", label: "Standard / mid-range" },
        { value: "premium", label: "Premium / high-end" },
        { value: "unknown", label: "Not sure yet" },
      ],
      helpText: "Complements project finish level in Step 4.",
    },
    {
      questionKey: "bathroom.tile_extent",
      label: "How much wall tiling is included?",
      type: "select",
      required: false,
      affectsEstimate: true,
      options: [
        { value: "full", label: "Full height" },
        { value: "partial", label: "Partial height" },
        { value: "unknown", label: "Not sure yet" },
      ],
    },
    {
      questionKey: "bathroom.fixtures_client_supplied",
      label: "Are fixtures supplied by the client?",
      type: "select",
      required: false,
      affectsEstimate: false,
      options: [
        { value: "yes", label: "Yes — client supplied" },
        { value: "no", label: "No — we supply" },
        { value: "partial", label: "Some client supplied" },
      ],
    },
    {
      questionKey: "bathroom.waterproofing_included",
      label: "Is waterproofing included?",
      type: "select",
      required: false,
      affectsEstimate: true,
      options: [...YES_NO_UNSURE],
    },
    {
      questionKey: "bathroom.rubbish_removal",
      label: "Is rubbish removal included?",
      type: "select",
      required: false,
      affectsEstimate: false,
      options: [...YES_NO_UNSURE],
    },
  ],
  constraints: [
    {
      key: "live_house",
      label: "Is the home occupied?",
      slug: "bathroom-live-house",
    },
    {
      key: "apartment_access",
      label: "Apartment access restrictions",
      slug: "bathroom-apartment-access",
    },
    {
      key: "asbestos_risk",
      label: "Asbestos risk",
      slug: "bathroom-asbestos-risk",
    },
    {
      key: "limited_working_hours",
      label: "Limited working hours",
      slug: "bathroom-limited-hours",
    },
  ],
  likelyTrades: [
    "Builder / Carpenter",
    "Plumber",
    "Waterproofer",
    "Tiler",
    "Electrician",
    "Painter",
  ],
  benchmarkRates: {
    unit: "m²",
    low: 3500,
    typical: 5000,
    high: 7500,
  },
  estimateRules: {
    calculationType: "floor_area",
    requiredFactKeys: ["bathroom.floor_area_m2"],
    lowMultiplier: 0.85,
    highMultiplier: 1.25,
    layoutChangeModifier: 1.2,
  },
};
