import { YES_NO_UNSURE } from "@/lib/scope-templates/shared";
import type { ScopeTemplate } from "@/lib/scope-templates/types";

export const retainingWallTemplate: ScopeTemplate = {
  key: "retaining_wall",
  name: "Retaining Wall",
  workAreaTypeKey: "Retaining Wall",
  category: "Outdoor",
  aliases: [
    "retaining wall",
    "retaining",
    "block wall",
    "timber retaining",
    "concrete retaining",
  ],
  description: "Retaining wall construction including drainage, backfill and spoil removal.",
  requiredFacts: [
    {
      key: "retaining_wall.length_m",
      label: "Retaining wall length",
      unit: "m",
      required: true,
      extractionPatterns: [
        /retaining\s*wall\s*(?:around|about|approx(?:imately)?\.?|is)?\s*(\d+(?:\.\d+)?)\s*(?:m|met(?:re|er)s?|lm)\s*long/i,
        /(?:retaining\s*)?wall\s*(?:length|long|is)?\s*(\d+(?:\.\d+)?)\s*(?:m|met(?:re|er)s?)/i,
        /(\d+(?:\.\d+)?)\s*(?:m|met(?:re|er)s?|lm)\s*(?:long|length)?\s*(?:retaining\s*)?wall/i,
        /retaining\s*wall\s*(\d+(?:\.\d+)?)\s*(?:m|met(?:re|er)s?)/i,
      ],
      extractValue: (m) => m[1] ?? null,
    },
    {
      key: "retaining_wall.height_m",
      label: "Retaining wall height",
      unit: "m",
      required: true,
      extractionPatterns: [
        /retaining\s*wall\s*(?:around|about|approx(?:imately)?\.?|is)?\s*(\d+(?:\.\d+)?)\s*(?:m|met(?:re|er)s?)\s*(?:high|height|tall)/i,
        /(\d+(?:\.\d+)?)\s*(?:m|met(?:re|er)s?)\s*(?:high|height|tall)\s*(?:retaining\s*)?wall/i,
        /(?:retaining\s*)?wall\s*(?:height|high|tall|is)?\s*(\d+(?:\.\d+)?)\s*(?:m|met(?:re|er)s?)/i,
        /and\s+(\d+(?:\.\d+)?)\s*(?:m|met(?:re|er)s?)\s*high/i,
      ],
      extractValue: (m) => m[1] ?? null,
    },
  ],
  optionalFacts: [
    {
      key: "retaining_wall.carting_distance_m",
      label: "Carting distance",
      unit: "m",
      required: false,
      extractionPatterns: [
        /(\d+(?:\.\d+)?)\s*(?:m|met(?:re|er)s?)\s*carting/i,
        /carting\s*distance\s*(?:of|about|around|is)?\s*(\d+(?:\.\d+)?)\s*(?:m|met(?:re|er)s?)?/i,
      ],
      extractValue: (m) => m[1] ?? null,
    },
    {
      key: "retaining_wall.has_drainage",
      label: "Drainage required",
      required: false,
      extractionPatterns: [/\bdrainage\b/i, /\bagg\s*pipe\b/i, /\bweep\s*holes\b/i],
      extractValue: () => "yes",
    },
    {
      key: "retaining_wall.has_backfill",
      label: "Backfill required",
      required: false,
      extractionPatterns: [/\bbackfill\b/i, /\bback\s*fill\b/i],
      extractValue: () => "yes",
    },
    {
      key: "retaining_wall.has_spoil_removal",
      label: "Spoil removal required",
      required: false,
      extractionPatterns: [/\bspoil\b/i, /\bexcavation\s+waste\b/i],
      extractValue: () => "yes",
    },
    {
      key: "retaining_wall.machine_access",
      label: "Machine access",
      required: false,
      extractionPatterns: [
        /\bno\s+digger\b/i,
        /\bno\s+excavator\b/i,
        /\bhand\s+dig\b/i,
        /\bmachine\s+access\s+limited\b/i,
      ],
      extractValue: () => "no",
    },
  ],
  questions: [
    {
      questionKey: "retaining_wall.length_m",
      label: "Approximate wall length?",
      type: "number",
      unit: "m",
      required: true,
      affectsEstimate: true,
      placeholder: "e.g. 12",
    },
    {
      questionKey: "retaining_wall.height_m",
      label: "Approximate wall height?",
      type: "number",
      unit: "m",
      required: true,
      affectsEstimate: true,
      placeholder: "e.g. 1.2",
    },
    {
      questionKey: "retaining_wall.has_drainage",
      label: "Is drainage required?",
      type: "select",
      required: false,
      affectsEstimate: true,
      options: [...YES_NO_UNSURE],
    },
    {
      questionKey: "retaining_wall.has_backfill",
      label: "Is backfill required?",
      type: "select",
      required: false,
      affectsEstimate: true,
      options: [...YES_NO_UNSURE],
    },
    {
      questionKey: "retaining_wall.machine_access",
      label: "Is machine access available?",
      type: "select",
      required: false,
      affectsEstimate: true,
      options: [...YES_NO_UNSURE],
    },
    {
      questionKey: "retaining_wall.has_spoil_removal",
      label: "Is spoil removal required?",
      type: "select",
      required: false,
      affectsEstimate: true,
      options: [...YES_NO_UNSURE],
    },
    {
      questionKey: "retaining_wall.carting_distance_m",
      label: "What is the carting distance?",
      type: "number",
      unit: "m",
      required: false,
      affectsEstimate: false,
      placeholder: "e.g. 15",
    },
  ],
  constraints: [
    {
      key: "machine_access_limited",
      label: "Machine access limited",
      slug: "retaining-machine-access",
      driverSlug: "machinery-access-limited",
      hideWhenQuestionAnswered: "retaining_wall.machine_access",
    },
    {
      key: "engineering_consent_risk",
      label: "Engineering/consent risk",
      slug: "retaining-engineering-risk",
      followUp: {
        label: "Engineering/consent risk level",
        unit: "",
        valueKey: "severity",
        inputType: "select",
        options: [
          { value: "low", label: "Low" },
          { value: "typical", label: "Typical" },
          { value: "high", label: "High" },
        ],
      },
    },
    {
      key: "difficult_spoil_removal",
      label: "Difficult spoil removal",
      slug: "retaining-difficult-spoil",
    },
  ],
  likelyTrades: ["Builder", "Earthworks", "Drainage", "Engineer", "Labourer"],
  benchmarkRates: {
    unit: "m²",
    low: 550,
    typical: 850,
    high: 1300,
  },
  estimateRules: {
    calculationType: "wall_area",
    requiredFactKeys: ["retaining_wall.length_m", "retaining_wall.height_m"],
    lowMultiplier: 0.88,
    highMultiplier: 1.22,
  },
};
