import { YES_NO_UNSURE } from "@/lib/scopes/shared";
import { BATHROOM_MATERIAL_CATEGORIES } from "@/lib/scopes/material-categories";
import type { ScopeDefinition } from "@/lib/scopes/types";

export const bathroomRenovationScope: ScopeDefinition = {
  id: "bathroom_renovation",
  name: "Bathroom renovation",
  workAreaTypeKey: "Bathroom renovation",
  category: "Interior",
  aliases: [
    "bathroom",
    "shower",
    "vanity",
    "toilet",
    "waterproofing",
    "ensuite",
    "wet room",
  ],
  description:
    "Bathroom renovation including waterproofing, tiling, fixtures and layout changes.",
  requiredFacts: [
    {
      key: "bathroom.floor_area_m2",
      label: "Floor area",
      type: "number",
      unit: "m²",
      required: true,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Approximate bathroom floor area?",
      placeholder: "e.g. 6",
      extractionPatterns: [
        /bathroom\s*(?:floor\s*)?(?:area|size)?\s*(?:of|about|approx(?:imately)?\.?|is)?\s*(\d+(?:\.\d+)?)\s*(?:m2|m²|sqm)/i,
        /(\d+(?:\.\d+)?)\s*(?:m2|m²|sqm)\s*bathroom/i,
      ],
      extractValue: (m) => m[1] ?? null,
    },
    {
      key: "bathroom.finish_level",
      label: "Finish level",
      type: "select",
      required: true,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: BATHROOM_MATERIAL_CATEGORIES.questionText,
      options: BATHROOM_MATERIAL_CATEGORIES.categories.map(({ value, label }) => ({
        value,
        label,
      })),
    },
    {
      key: "bathroom.layout_changing",
      label: "Layout changing",
      type: "select",
      required: true,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Is the layout changing?",
      options: [...YES_NO_UNSURE],
      extractionPatterns: [/\blayout\s+chang/i, /\brelocat(e|ing)\s+(?:shower|toilet)/i],
      extractValue: () => "yes",
    },
    {
      key: "bathroom.tile_extent",
      label: "Tile extent",
      type: "select",
      required: true,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "How much wall tiling is included?",
      options: [
        { value: "full", label: "Full height" },
        { value: "partial", label: "Partial height" },
        { value: "unknown", label: "Not sure yet" },
      ],
    },
  ],
  optionalFacts: [
    {
      key: "bathroom.fixtures_client_supplied",
      label: "Client-supplied fixtures",
      type: "select",
      required: false,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Are fixtures supplied by the client?",
      options: [
        { value: "yes", label: "Yes — client supplied" },
        { value: "no", label: "No — we supply" },
        { value: "partial", label: "Some client supplied" },
      ],
      extractionPatterns: [
        /\bclient\s+suppl(?:y|ied)\s+fixtures\b/i,
        /\bfixtures\s+(?:by|from)\s+(?:the\s+)?client\b/i,
        /\bclient\s+(?:is\s+)?suppl(?:y|ying).*(?:vanity|toilet|tiles)/i,
      ],
      extractValue: () => "yes",
    },
    {
      key: "bathroom.tiles_supplied_by",
      label: "Tiles supplied by",
      type: "select",
      required: false,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Are tiles supplied by the client or contractor?",
      options: [
        { value: "contractor", label: "Contractor supplies" },
        { value: "client", label: "Client supplies" },
        { value: "unknown", label: "Not sure yet" },
      ],
      extractionPatterns: [
        /\bclient\s+(?:is\s+)?suppl(?:y|ying)\s+tiles\b/i,
        /\btiles\s+(?:by|from)\s+(?:the\s+)?client\b/i,
      ],
      extractValue: () => "client",
    },
    {
      key: "bathroom.demolition_included",
      label: "Demolition",
      type: "select",
      required: false,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Is demolition of the existing bathroom included?",
      options: [...YES_NO_UNSURE],
      extractionPatterns: [/\bdemo(?:lish)?\b/i, /\bstrip\s*out\b/i],
      extractValue: () => "yes",
    },
    {
      key: "bathroom.plumbing_relocation",
      label: "Plumbing relocation",
      type: "select",
      required: false,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Is plumbing being relocated?",
      options: [...YES_NO_UNSURE],
      extractionPatterns: [
        /\bplumb(?:ing)?\s+relocat/i,
        /\brelocat(?:e|ing)\s+(?:shower|toilet|vanity)/i,
      ],
      extractValue: () => "yes",
    },
    {
      key: "bathroom.electrical_allowance",
      label: "Electrical allowance",
      type: "select",
      required: false,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Is electrical work included?",
      options: [...YES_NO_UNSURE],
      extractionPatterns: [/\belectrical\b/i, /\bgpo\b/i, /\blighting\b/i],
      extractValue: () => "yes",
    },
    {
      key: "bathroom.rubbish_removal",
      label: "Rubbish removal",
      type: "select",
      required: false,
      affectsEstimate: false,
      affectsConfidence: true,
      questionText: "Is rubbish removal required?",
      options: [...YES_NO_UNSURE],
      extractionPatterns: [/\brubbish\b/i, /\bwaste\s+removal\b/i, /\bskip\b/i],
      extractValue: () => "yes",
    },
    {
      key: "bathroom.occupied_home",
      label: "Occupied home",
      type: "select",
      required: false,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Is the home occupied during the work?",
      options: [...YES_NO_UNSURE],
      extractionPatterns: [/\boccupied\s+(?:home|house)\b/i, /\blive\s+in\b/i],
      extractValue: () => "yes",
    },
    {
      key: "bathroom.waterproofing_included",
      label: "Waterproofing",
      type: "select",
      required: false,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Is waterproofing included?",
      options: [...YES_NO_UNSURE],
      extractionPatterns: [/\bwaterproof/i],
      extractValue: () => "yes",
    },
  ],
  pricingDrivers: [
    "bathroom.floor_area_m2",
    "bathroom.finish_level",
    "bathroom.layout_changing",
    "bathroom.tile_extent",
    "bathroom.waterproofing_included",
    "bathroom.demolition_included",
    "bathroom.plumbing_relocation",
    "bathroom.electrical_allowance",
  ],
  constraints: [
    {
      key: "live_house",
      label: "Occupied home",
      questionText: "Is the home occupied?",
      slug: "bathroom-live-house",
    },
    {
      key: "apartment_access",
      label: "Apartment access",
      questionText: "Are there apartment access restrictions?",
      slug: "bathroom-apartment-access",
    },
    {
      key: "asbestos_risk",
      label: "Asbestos risk",
      questionText: "Is there an asbestos risk?",
      slug: "bathroom-asbestos-risk",
    },
    {
      key: "limited_working_hours",
      label: "Limited working hours",
      questionText: "Are working hours restricted?",
      slug: "bathroom-limited-hours",
    },
  ],
  likelyTrades: [
    "Builder / Carpenter",
    "Plumber",
    "Waterproofer",
    "Tiler",
    "Electrician",
    "Painter",
  ],
  assumptions: [
    "Standard bathroom renovation sequence assumed.",
    "Existing services locations to be confirmed on site.",
  ],
  confidenceRules: {
    measurementFactKeys: [
      "bathroom.floor_area_m2",
      "bathroom.finish_level",
      "bathroom.layout_changing",
      "bathroom.tile_extent",
    ],
    highImpactOptionalKeys: [
      "bathroom.waterproofing_included",
      "bathroom.demolition_included",
      "bathroom.plumbing_relocation",
      "bathroom.fixtures_client_supplied",
      "bathroom.tiles_supplied_by",
      "bathroom.occupied_home",
    ],
  },
  benchmarkRates: { unit: "m²", low: 3500, typical: 5000, high: 7500 },
  estimateRules: {
    calculationType: "floor_area",
    requiredFactKeys: [
      "bathroom.floor_area_m2",
      "bathroom.finish_level",
      "bathroom.layout_changing",
      "bathroom.tile_extent",
    ],
    layoutChangeModifier: 1.2,
  },
};
