import { YES_NO_UNSURE } from "@/lib/scopes/shared";
import type { ScopeDefinition } from "@/lib/scopes/types";

export const bathroomRenovationScope: ScopeDefinition = {
  id: "bathroom_renovation",
  name: "Bathroom renovation",
  workAreaTypeKey: "Bathroom renovation",
  category: "Interior",
  aliases: [
    "bathroom",
    "shower",
    "vanity",
    "toilet",
    "waterproofing",
    "ensuite",
    "wet room",
  ],
  description:
    "Bathroom renovation including waterproofing, tiling, fixtures and layout changes.",
  requiredFacts: [
    {
      key: "bathroom.floor_area_m2",
      label: "Floor area",
      type: "number",
      unit: "m²",
      required: true,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Approximate bathroom floor area?",
      placeholder: "e.g. 6",
      extractionPatterns: [
        /bathroom\s*(?:floor\s*)?(?:area|size)?\s*(?:of|about|approx(?:imately)?\.?|is)?\s*(\d+(?:\.\d+)?)\s*(?:m2|m²|sqm)/i,
        /(\d+(?:\.\d+)?)\s*(?:m2|m²|sqm)\s*bathroom/i,
      ],
      extractValue: (m) => m[1] ?? null,
    },
    {
      key: "bathroom.finish_level",
      label: "Finish level",
      type: "select",
      required: true,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "What finish level is expected?",
      options: [
        { value: "budget", label: "Budget / basic" },
        { value: "standard", label: "Standard / mid-range" },
        { value: "premium", label: "Premium / high-end" },
        { value: "unknown", label: "Not sure yet" },
      ],
    },
    {
      key: "bathroom.layout_changing",
      label: "Layout changing",
      type: "select",
      required: true,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Is the layout changing?",
      options: [...YES_NO_UNSURE],
      extractionPatterns: [/\blayout\s+chang/i, /\brelocat(e|ing)\s+(?:shower|toilet)/i],
      extractValue: () => "yes",
    },
    {
      key: "bathroom.tile_extent",
      label: "Tile extent",
      type: "select",
      required: true,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "How much wall tiling is included?",
      options: [
        { value: "full", label: "Full height" },
        { value: "partial", label: "Partial height" },
        { value: "unknown", label: "Not sure yet" },
      ],
    },
  ],
  optionalFacts: [
    {
      key: "bathroom.fixtures_client_supplied",
      label: "Client-supplied fixtures",
      type: "select",
      required: false,
      affectsEstimate: false,
      affectsConfidence: false,
      questionText: "Are fixtures supplied by the client?",
      options: [
        { value: "yes", label: "Yes — client supplied" },
        { value: "no", label: "No — we supply" },
        { value: "partial", label: "Some client supplied" },
      ],
    },
    {
      key: "bathroom.rubbish_removal",
      label: "Rubbish removal",
      type: "select",
      required: false,
      affectsEstimate: false,
      affectsConfidence: false,
      questionText: "Is rubbish removal required?",
      options: [...YES_NO_UNSURE],
    },
    {
      key: "bathroom.waterproofing_included",
      label: "Waterproofing",
      type: "select",
      required: false,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Is waterproofing included?",
      options: [...YES_NO_UNSURE],
      extractionPatterns: [/\bwaterproof/i],
      extractValue: () => "yes",
    },
  ],
  pricingDrivers: [
    "bathroom.floor_area_m2",
    "bathroom.finish_level",
    "bathroom.layout_changing",
    "bathroom.tile_extent",
    "bathroom.waterproofing_included",
  ],
  constraints: [
    {
      key: "live_house",
      label: "Occupied home",
      questionText: "Is the home occupied?",
      slug: "bathroom-live-house",
    },
    {
      key: "apartment_access",
      label: "Apartment access",
      questionText: "Are there apartment access restrictions?",
      slug: "bathroom-apartment-access",
    },
    {
      key: "asbestos_risk",
      label: "Asbestos risk",
      questionText: "Is there an asbestos risk?",
      slug: "bathroom-asbestos-risk",
    },
    {
      key: "limited_working_hours",
      label: "Limited working hours",
      questionText: "Are working hours restricted?",
      slug: "bathroom-limited-hours",
    },
  ],
  likelyTrades: [
    "Builder / Carpenter",
    "Plumber",
    "Waterproofer",
    "Tiler",
    "Electrician",
    "Painter",
  ],
  assumptions: [
    "Standard bathroom renovation sequence assumed.",
    "Existing services locations to be confirmed on site.",
  ],
  confidenceRules: {
    measurementFactKeys: [
      "bathroom.floor_area_m2",
      "bathroom.finish_level",
      "bathroom.layout_changing",
      "bathroom.tile_extent",
    ],
    highImpactOptionalKeys: ["bathroom.waterproofing_included"],
  },
  benchmarkRates: { unit: "m²", low: 3500, typical: 5000, high: 7500 },
  estimateRules: {
    calculationType: "floor_area",
    requiredFactKeys: [
      "bathroom.floor_area_m2",
      "bathroom.finish_level",
      "bathroom.layout_changing",
      "bathroom.tile_extent",
    ],
    layoutChangeModifier: 1.2,
  },
};
