import { YES_NO_UNSURE } from "@/lib/scopes/shared";
import { RETAINING_WALL_MATERIAL_CATEGORIES } from "@/lib/scopes/material-categories";
import type { ScopeDefinition } from "@/lib/scopes/types";

export const retainingWallScope: ScopeDefinition = {
  id: "retaining_wall",
  name: "Retaining Wall",
  workAreaTypeKey: "Retaining Wall",
  category: "Outdoor",
  aliases: [
    "retaining wall",
    "retaining",
    "block wall",
    "timber retaining",
    "concrete retaining",
  ],
  description:
    "Retaining wall construction including drainage, backfill and spoil removal.",
  requiredFacts: [
    {
      key: "retaining_wall.length_m",
      label: "Wall length",
      type: "number",
      unit: "m",
      required: true,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Approximate wall length?",
      placeholder: "e.g. 12",
      extractionPatterns: [
        /retaining\s*wall\s*(?:around|about|approx(?:imately)?\.?|is)?\s*(\d+(?:\.\d+)?)\s*(?:m|met(?:re|er)s?|lm)\s*long/i,
        /(\d+(?:\.\d+)?)\s*(?:m|met(?:re|er)s?|lm)\s*(?:long|length)?\s*(?:retaining\s*)?wall/i,
      ],
      extractValue: (m) => m[1] ?? null,
    },
    {
      key: "retaining_wall.height_m",
      label: "Wall height",
      type: "number",
      unit: "m",
      required: true,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Approximate wall height?",
      placeholder: "e.g. 1.2",
      extractionPatterns: [
        /(\d+(?:\.\d+)?)\s*(?:m|met(?:re|er)s?)\s*(?:high|height|tall)\s*(?:retaining\s*)?wall/i,
      ],
      extractValue: (m) => m[1] ?? null,
    },
    {
      key: "retaining_wall.material",
      label: "Wall material",
      type: "select",
      required: true,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: RETAINING_WALL_MATERIAL_CATEGORIES.questionText,
      options: RETAINING_WALL_MATERIAL_CATEGORIES.categories.map(({ value, label }) => ({
        value,
        label,
      })),
      extractionPatterns: [
        /\btimber\s+retaining\b/i,
        /\bblock\s+wall\b/i,
        /\bconcrete\s+sleeper\b/i,
        /\bconcrete\s+retaining\b/i,
        /\bkeystone\b/i,
        /\bstone\s+wall\b/i,
      ],
      extractValue: (m) => {
        const text = m[0].toLowerCase();
        if (text.includes("timber")) return "timber";
        if (text.includes("keystone")) return "keystone";
        if (text.includes("stone")) return "stone";
        if (text.includes("sleeper")) return "concrete_sleeper";
        if (text.includes("block")) return "concrete_block";
        if (text.includes("concrete")) return "concrete_sleeper";
        return null;
      },
    },
    {
      key: "retaining_wall.has_drainage",
      label: "Drainage",
      type: "select",
      required: true,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Is drainage required?",
      options: [...YES_NO_UNSURE],
      extractionPatterns: [/\bdrainage\b/i, /\bagg\s*pipe\b/i],
      extractValue: () => "yes",
    },
    {
      key: "retaining_wall.machine_access",
      label: "Machine access",
      type: "select",
      required: true,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Is machine access available?",
      options: [...YES_NO_UNSURE],
      extractionPatterns: [
        /\bno\s+digger\b/i,
        /\bmachine\s+access\s+limited\b/i,
        /\bpoor\s+access\b/i,
        /\bhand\s+dig(?:ging)?\b/i,
        /\bno\s+machine\s+access\b/i,
      ],
      extractValue: () => "no",
    },
  ],
  optionalFacts: [
    {
      key: "retaining_wall.has_backfill",
      label: "Backfill",
      type: "select",
      required: false,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Is backfill required?",
      options: [...YES_NO_UNSURE],
      extractionPatterns: [/\bbackfill\b/i],
      extractValue: () => "yes",
    },
    {
      key: "retaining_wall.has_spoil_removal",
      label: "Spoil removal",
      type: "select",
      required: false,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Is spoil removal required?",
      options: [...YES_NO_UNSURE],
      extractionPatterns: [/\bspoil\b/i],
      extractValue: () => "yes",
    },
    {
      key: "retaining_wall.carting_distance_m",
      label: "Carting distance",
      type: "number",
      unit: "m",
      required: false,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "What is the carting distance?",
      placeholder: "e.g. 15",
      extractionPatterns: [
        /(\d+(?:\.\d+)?)\s*(?:m|met(?:re|er)s?)\s*carting/i,
      ],
      extractValue: (m) => m[1] ?? null,
    },
    {
      key: "retaining_wall.surcharge_loading",
      label: "Surcharge / loading risk",
      type: "select",
      required: false,
      affectsEstimate: true,
      affectsConfidence: true,
      questionText: "Is there surcharge or loading above the wall?",
      options: [...YES_NO_UNSURE],
      extractionPatterns: [
        /\bsurcharge\b/i,
        /\bloading\s+(?:above|on)\b/i,
        /\bdriveway\s+above\b/i,
      ],
      extractValue: () => "yes",
    },
  ],
  pricingDrivers: [
    "retaining_wall.length_m",
    "retaining_wall.height_m",
    "retaining_wall.material",
    "retaining_wall.has_drainage",
    "retaining_wall.machine_access",
    "retaining_wall.has_backfill",
    "retaining_wall.has_spoil_removal",
    "retaining_wall.carting_distance_m",
    "retaining_wall.surcharge_loading",
  ],
  constraints: [
    {
      key: "machine_access_limited",
      label: "Machine access limited",
      questionText: "Is machine access limited?",
      slug: "retaining-machine-access",
      driverSlug: "machinery-access-limited",
      hideWhenFactAnswered: "retaining_wall.machine_access",
    },
    {
      key: "engineering_consent_risk",
      label: "Engineering/consent risk",
      questionText: "Is there engineering or consent risk?",
      slug: "retaining-engineering-risk",
      followUp: {
        label: "Risk level",
        unit: "",
        valueKey: "severity",
        inputType: "select",
        options: [
          { value: "low", label: "Low" },
          { value: "typical", label: "Typical" },
          { value: "high", label: "High" },
        ],
      },
    },
    {
      key: "difficult_spoil_removal",
      label: "Difficult spoil removal",
      questionText: "Is spoil removal difficult?",
      slug: "retaining-difficult-spoil",
    },
  ],
  likelyTrades: ["Builder", "Earthworks", "Drainage", "Engineer", "Labourer"],
  assumptions: [
    "Standard retaining wall construction assumed.",
    "Engineering may be required for walls over 1.5m.",
  ],
  confidenceRules: {
    measurementFactKeys: [
      "retaining_wall.length_m",
      "retaining_wall.height_m",
      "retaining_wall.material",
      "retaining_wall.has_drainage",
      "retaining_wall.machine_access",
    ],
    highImpactOptionalKeys: [
      "retaining_wall.has_backfill",
      "retaining_wall.has_spoil_removal",
      "retaining_wall.carting_distance_m",
      "retaining_wall.surcharge_loading",
    ],
  },
  benchmarkRates: { unit: "m²", low: 550, typical: 850, high: 1300 },
  estimateRules: {
    calculationType: "wall_area",
    requiredFactKeys: [
      "retaining_wall.length_m",
      "retaining_wall.height_m",
      "retaining_wall.material",
      "retaining_wall.has_drainage",
      "retaining_wall.machine_access",
    ],
  },
};
